config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
resources :posts , only: [:index, :new, :create]
get 'latest', to: 'posts#latest'

resources :contacts, only: [:new, :create] do
  collection do
    post 'confirm'
    post 'back'
    get 'done'
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
  validates :message, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :price_total, presence: true
  validates :year, presence: true
  validates :distance, presence: true
  validates :inspection, presence: true
  validates :color, presence: true
  validates :car_name, presence: true
  validates :car_model, presence: true
  validates :rec_point, presence: true  
  validates :grade, presence: true
  validates :image, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:id_number,:name])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.valid?
      render template: 'contacts/confirm'
    else
      redirect_to new_contact_path, alert: @contact.errors.full_messages.join(", ")
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_contacts_path
    else
      flash[:alert] = @contact.errors.full_messages.join(", ")
      @contact = Contact.new
      render :new
    end
  end

  def done
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :phone_number, :message)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  @post = Post.first(3)
  end
  def latest
    @post = Post.all.order(created_at: :desc).page(params[:page]).per(4)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to '/'
      else
      render :new, status: :unprocessable_entity
    end
  end


  private

  def posts_params
    params.require(:post).permit(:image, :price_total, :year, :distance, :inspection, :color, :car_name, :car_model, :rec_point, :grade)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contacts/confirm.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-md-10 offset-md-1">

      <table class="table">
        <tbody>
          <tr>
            <td class="text-right">お名前</td>
            <td><%= @contact.name %></td>
          </tr>
          <tr>
            <td class="text-right mt-3">メールアドレス</td>
            <td><%= @contact.email %></td>
          </tr>
          <tr>
            <td class="text-right mt-3">件名</td>
            <td><%= @contact.phone_number %></td>
          </tr>
          <tr>
            <td class="text-right mt-3">メッセージ</td>
            <td style="white-space: pre-wrap;"><%= @contact.message %></td>
          </tr>
        </tbody>
      </table>

      <div class="d-flex">
        <div class="mr-3">
<%= form_with model: @contact, url: contacts_path, method: :post, local: true do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :phone_number %>
  <%= f.hidden_field :message %>
  <%= f.submit '送信', class: "btn btn-success" %>
<% end %>
        </div>

        <div>
        <%= form_with model: @contact, url: back_contacts_path do |f| %>
          <%= f.hidden_field :name %>
          <%= f.hidden_field :email %>
          <%= f.hidden_field :phone_number %>
          <%= f.hidden_field :message %>
          <div><%= f.submit '入力画面に戻る', class: "btn btn-info" %></div>
        <% end %>
        </div>
      </div>


    </div>
  </div>
</div>

app/views/contacts/done.html.erb
<div class="done-text-top">
  <h5 class="text-center">お問い合わせいただき、ありがとうございます。<br>
  近日中にあらためてご連絡いたします。</h5>
</div>

<div class="done-text-bottom">
  <%= link_to '最初のページに戻る', root_path, class: "link-done-botton" %>
</div>

app/views/contacts/new.html.erb
<%= render "shared/header" %>

<div class="contact-form-container">
  <div class="contact-form">
    <div class="contact-title">お問い合わせフォーム</div>
    <div class="contact-attention">気になるお車や、査定のご予約などお気軽にご記入ください。</div>
    
    <div class="mb-2 text-center">
      <%= flash[:alert] %>
    </div>

    <%= form_with model: @contact, url: confirm_contacts_path, local: true, data: { turbo: false } do |f| %>
      <div class="form-group">
        <%= f.label :name, 'お名前' %><span class="text-danger">*</span>
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %><span class="text-danger">*</span>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :phone_number, '電話番号' %><span class="text-danger">*</span>
        <%= f.text_field :phone_number, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :message, 'メッセージ' %><span class="text-danger">*</span>
        <%= f.text_area :message, size: '10x10', class: 'form-control' %>
      </div>

      <div class="text-center">
        <%= f.submit '入力内容確認', class: "btn btn-outline-info bg-white custom-btn" %>
      </div>
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
<link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
  <title>IMPROVE</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Sawarabi+Mincho&display=swap" rel="stylesheet">
  
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@latest/swiper-bundle.min.css">
<script src="https://cdn.jsdelivr.net/npm/swiper@latest/swiper-bundle.min.js"></script>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/orders/index.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag "item-sample.png", class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= "商品名" %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= '999,999,999' %></p>
          <p class='item-price-sub-text'><%= '配送料負担' %></p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= "販売価格" %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <div id="number-form" class="input-default"></div>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <div id="expiry-form" class="input-default"></div>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <div id="cvc-form" class="input-default"></div>
      </div>
    </div>
    <%# /カード情報の入力 %>
    
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        配送先入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :hoge, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    <%# /配送先の入力 %>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn", id:"button" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「IMPROVE」帯部分 %>
  <div class='title-contents'>
      <div class='search-bar-contents'>
        <%# <%= link_to image_tag("carshop-icon.png", class:"carshop-icon"), "/" %>     
         <div class="site-title">
           <%= link_to '(株)improve', "#", class: "carshop-title" %></li>
      </div>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
    <h2 class='service-title'>
      販売・買取も対応
    </h2>
    <p class='service-explain'>
      出張査定、出張納車も対応中
    </p>
    <p class='service-explain'>
      気軽にお電話　☎000-000-0000 お待ちしております
    </p>
  </div>
  <%# /画面上部の「IMPROVE」帯部分  %>

<%# 商品一覧 %>
<div class='item-contents'>
      <div class='lists-left'>
        <nav class="nav-links">
        <%= link_to '最新の車を見る', latest_path, class: "nav-link new-list" %>
        <%= link_to 'メーカー', "#", class: "nav-link brand-list" %>
        <%= link_to 'お問い合わせ', new_contact_path, class: "nav-link contact-list" %>
        </nav>
      </div>

  <div class='title'>販売車両一覧</div>
  <div class="subtitle">
      <%= image_tag 'carshop-blueline.png' , size: '6x15' ,class: "blueline-image" %>
    新規入庫車
  </div>

<div class="swiper-container">
  <div class="swiper-wrapper">
    <% @post.each do |post| %>
      <div class="swiper-slide">
         <%= image_tag post.image,class: "slide-image" %> 
        <div class="slide-content">
          <h3 class="slide-title"><%= post.car_name %></h3>
          <p class="slide-price">¥<%= post.price_total %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="swiper-pagination"></div>
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</div>
    <div class='more-button'>
      <%= link_to 'もっと見る', latest_path, class: 'more-link' %>
    </div>
<%# /商品一覧 %>

<% if user_signed_in? %>
<%= link_to '新入庫を追加する', new_post_path, class: "exhibit-btn" %>
<% end %>
<%= render "shared/footer" %>

<div id="slideshow">   </div>

app/views/posts/latest.html.erb
<%= render "shared/header" %>

<div class="latest-list">
  <% @post.each do |post| %>
    <div class="car-item">
      <h2><%= post.car_name %></h2>
      <p><%= post.grade %></p>
      <p>価格: <%= post.price_total %>円</p>
         <%= image_tag post.image,class: "latest-image" %> 
    </div>
  <% end %>
</div>
<div class="pagination">
<%= paginate @post %>
</div>

<%= render "shared/footer" %>

app/views/posts/new.html.erb
<%= render "shared/header"%>

<%= form_with model: @post, url: posts_path, local: true do |f| %>

<%= render 'shared/error_messages', model: f.object %>
<div class="registration-main">
<div class='form-wrap'>
  
  <div class='form-header'>
    <h1 class='form-header-text'>
      車の登録情報入力
    </h1>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">写真</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.file_field :image, id:"item-image" %>
  </div>
  


  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メーカー</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :car_model, class:"input-default", id:"car_model", placeholder:"トヨタ・日産等", autofocus: true %>
  </div>
  
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">車種</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :car_name, class:"input-default", id:"car_name", placeholder:"ハリアー・アクア" %>
  </div>
  
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">グレード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :grade, class:"input-default", id:"grade", placeholder:"" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">総額</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.number_field :price_total, class:"input-default", id:"price_total", placeholder:"半角数字のみ例）100000" %>
  </div>

    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">色</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :color, class:"input-default", id:"color", placeholder:"" %>
  </div>

      <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">走行距離</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.number_field :distance, class:"input-default", id:"distance", placeholder:"例）100000" %>
  </div>

    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">年式</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.number_field :year, class:"input-default", id:"year", placeholder:"例）2014" %>
  </div>

    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">車検期限</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.number_field :inspection, class:"input-default", id:"inspection", placeholder:"例）24/10" %>
  </div>

    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">おすすめポイント</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :rec_point, class:"input-default", id:"rec_point", placeholder:"" %>
  </div>

  <div class='exhibit-btn-wrap'>
    <%= f.submit "投稿する" ,class:"exhibit-btn" %>
  </div>

</div>

</div>
<% end %>

<%= render "shared/footer"%>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>(株)IMPROVE</h2>
      <ul>
        <li><%= link_to '会社概要', "#", class: "footer-link" %></li>
        <li><%= link_to '何か', "#", class: "footer-link" %></li>
        <li><%= link_to '何か', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>車両一覧</h2>
      <ul>
        <li><%= link_to '最新の車を見る', "#", class: "footer-link" %></li>
        <li><%= link_to 'メーカーで探す', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>サイトについて</h2>
      <ul>
        <li><%= link_to 'ガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'ロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <p>© IMPROVE</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
  <header class='top-page-header'>
  <div class="nav1">
         <li><%= link_to image_tag("carshop-icon.png", class:"carshop-icon"), "/" %></li>
          <ul class="top-left">
        <li><%= link_to '会社概要', "#", class: "headertop-link" %></li>
        <li><%= link_to '何か', "#", class: "headertop-link" %></li>
        <li><%= link_to '何か', "#", class: "headertop-link" %></li>
         </ul>
        <ul class="top-left">     
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐%>
      <%# <li><%= link_to current_user.nickname, "#", class: "user-nickname" </li> %>
      <%# <li><%= link_to 'ログアウト', "#", data: {turbo_method: :delete}, class: "logout" </li> %>
      <li><%= link_to '従業員の方はコチラ', new_user_registration_path, class: "login" %></li>
      <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐%>
      </ul>
  </div>



</header>